repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        name: Check for merge conflict markers
      - id: check-yaml
        name: Check YAML syntax
        args: [--unsafe]
      - id: trailing-whitespace
        name: Remove trailing whitespaces
        args: [--markdown-linebreak-ext=md]
      - id: no-commit-to-branch
        name: Ensure committing to allowed branch
      - id: requirements-txt-fixer
        name: Sort entries in requirements.txt
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: Lint Markdown files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.3
    hooks:
      - id: check-github-workflows
