---
name: ✨ Feature request
description: Suggest a new feature for MkDocs deployment.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to open this Issue!**

        💡 **Please note**
        This Issue type is meant for suggesting features to the MkDocs deployment itself. For missing
        documentation or guidance, please use the [Documentation request](https://github.com/TimGrt/Ansible-Hackathon/issues/new?assignees=&labels=feature&template=documentation_request.yml) issue type.

  - type: input
    id: contact
    attributes:
      label: ☎️ Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    attributes:
      label: Summary
      description: >
        Describe the new feature/improvement you would like briefly below.

        What's the problem this feature will solve?

    validations:
      required: true
