---
name: Linting
on:
  workflow_dispatch:
  pull_request:

jobs:
  md-lint:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: avto-dev/markdown-lint@v1.5.0
